language: php
php:
  - 7.0
  - 7.1
sudo: false
dist: trusty
before_install:
  - composer self-update --no-interaction || true
before_script:
  - composer install --no-interaction
  - pecl update-channels; pecl install grpc-1.3.2
script:
  - phpunit --configuration phpunit.xml.dist
matrix:
  fast_finish: true
